// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf3FO9XE_fGahbv439cWjZRXnN_iIqPHE',
    appId: '1:297266649436:web:60dfff8d7319ea46040999',
    messagingSenderId: '297266649436',
    projectId: 'testing-client-project',
    authDomain: 'testing-client-project.firebaseapp.com',
    storageBucket: 'testing-client-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHW3v2OL3DE95KcXtuLZq7l2qymwKtQCg',
    appId: '1:297266649436:android:3508f09a9613aefb040999',
    messagingSenderId: '297266649436',
    projectId: 'testing-client-project',
    storageBucket: 'testing-client-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjy707nY2TMUk7leLBvQIdi81V0a4eoGU',
    appId: '1:297266649436:ios:65b4a6e473ad7cb3040999',
    messagingSenderId: '297266649436',
    projectId: 'testing-client-project',
    storageBucket: 'testing-client-project.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjy707nY2TMUk7leLBvQIdi81V0a4eoGU',
    appId: '1:297266649436:ios:65b4a6e473ad7cb3040999',
    messagingSenderId: '297266649436',
    projectId: 'testing-client-project',
    storageBucket: 'testing-client-project.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf3FO9XE_fGahbv439cWjZRXnN_iIqPHE',
    appId: '1:297266649436:web:505c4af2b1c610d6040999',
    messagingSenderId: '297266649436',
    projectId: 'testing-client-project',
    authDomain: 'testing-client-project.firebaseapp.com',
    storageBucket: 'testing-client-project.firebasestorage.app',
  );
}
